/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.unifacema.gui;

/**
 *
 * @author talison
 */
public class Ajuda extends javax.swing.JDialog {

    /**
     * Creates new form Ajuda
     */
    public Ajuda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        barraTopo = new javax.swing.JPanel();
        btAjuda = new javax.swing.JButton();
        btSobre = new javax.swing.JButton();
        btSuporte = new javax.swing.JButton();
        conteudo = new javax.swing.JPanel();
        telaAjuda = new javax.swing.JPanel();
        telaSobre = new javax.swing.JPanel();
        telaSup = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ajuda");
        setBackground(new java.awt.Color(51, 51, 51));

        bg.setBackground(new java.awt.Color(0, 102, 102));

        barraTopo.setBackground(new java.awt.Color(51, 51, 51));
        barraTopo.setForeground(new java.awt.Color(255, 255, 255));

        btAjuda.setBackground(new java.awt.Color(0, 102, 102));
        btAjuda.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btAjuda.setForeground(new java.awt.Color(255, 255, 255));
        btAjuda.setText("Ajuda");
        btAjuda.setBorderPainted(false);
        btAjuda.setFocusPainted(false);

        btSobre.setBackground(new java.awt.Color(0, 102, 102));
        btSobre.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btSobre.setForeground(new java.awt.Color(255, 255, 255));
        btSobre.setText("Sobre");
        btSobre.setBorderPainted(false);
        btSobre.setFocusPainted(false);

        btSuporte.setBackground(new java.awt.Color(0, 102, 102));
        btSuporte.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btSuporte.setForeground(new java.awt.Color(255, 255, 255));
        btSuporte.setText("Suporte");
        btSuporte.setBorderPainted(false);
        btSuporte.setFocusPainted(false);

        javax.swing.GroupLayout barraTopoLayout = new javax.swing.GroupLayout(barraTopo);
        barraTopo.setLayout(barraTopoLayout);
        barraTopoLayout.setHorizontalGroup(
            barraTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraTopoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btAjuda, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btSobre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btSuporte, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        barraTopoLayout.setVerticalGroup(
            barraTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barraTopoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(barraTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSobre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAjuda, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSuporte, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        conteudo.setBackground(new java.awt.Color(0, 102, 102));
        conteudo.setForeground(new java.awt.Color(255, 255, 255));
        conteudo.setLayout(new java.awt.CardLayout());

        telaAjuda.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout telaAjudaLayout = new javax.swing.GroupLayout(telaAjuda);
        telaAjuda.setLayout(telaAjudaLayout);
        telaAjudaLayout.setHorizontalGroup(
            telaAjudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        telaAjudaLayout.setVerticalGroup(
            telaAjudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 545, Short.MAX_VALUE)
        );

        conteudo.add(telaAjuda, "card2");

        telaSobre.setBackground(new java.awt.Color(0, 102, 102));
        telaSobre.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout telaSobreLayout = new javax.swing.GroupLayout(telaSobre);
        telaSobre.setLayout(telaSobreLayout);
        telaSobreLayout.setHorizontalGroup(
            telaSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        telaSobreLayout.setVerticalGroup(
            telaSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 545, Short.MAX_VALUE)
        );

        conteudo.add(telaSobre, "card3");

        telaSup.setBackground(new java.awt.Color(0, 102, 102));
        telaSup.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout telaSupLayout = new javax.swing.GroupLayout(telaSup);
        telaSup.setLayout(telaSupLayout);
        telaSupLayout.setHorizontalGroup(
            telaSupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        telaSupLayout.setVerticalGroup(
            telaSupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 545, Short.MAX_VALUE)
        );

        conteudo.add(telaSup, "card4");

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barraTopo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(conteudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(barraTopo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(conteudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ajuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ajuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ajuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ajuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Ajuda dialog = new Ajuda(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraTopo;
    private javax.swing.JPanel bg;
    private javax.swing.JButton btAjuda;
    private javax.swing.JButton btSobre;
    private javax.swing.JButton btSuporte;
    private javax.swing.JPanel conteudo;
    private javax.swing.JPanel telaAjuda;
    private javax.swing.JPanel telaSobre;
    private javax.swing.JPanel telaSup;
    // End of variables declaration//GEN-END:variables
}
