/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.unifacema.gui;

import br.edu.unifacema.model.bean.Cliente;
import br.edu.unifacema.model.bean.Quarto;
import br.edu.unifacema.model.dao.ClienteDAO;
import br.edu.unifacema.model.dao.QuartoDAO;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author talison
 */
public class Home extends javax.swing.JFrame {
    
    QuartoDAO qtdao = new QuartoDAO();
    ClienteDAO cldao = new ClienteDAO();

    /**
     * Creates new form Home
     */
    public Home() {   
    
        
        
        initComponents();
        
        DefaultTableModel tabela1 = (DefaultTableModel) tabelaMenu1.getModel();
        DefaultTableModel tabela2 = (DefaultTableModel) qtTabela.getModel();
        tabelaMenu1.setRowSorter(new TableRowSorter(tabela1));
        qtTabela.setRowSorter(new TableRowSorter(tabela2));
       
        combBoxP1();
        tabelaCliente();
        tabelaQuarto();
           
    }
    
    public void tabelaQuarto(){
        DefaultTableModel tabela2 = (DefaultTableModel) qtTabela.getModel();
        tabela2.setNumRows(0);
        QuartoDAO qtDao = new QuartoDAO();
        
        for(Quarto c : qtDao.read()){
        
            tabela2.addRow(new Object[]{
                c.getNumero(),
                c.getAndar(),
                c.getPreco(),
                c.getEstado(),
                c.getPeriodo()
            });
            
        }
    }
    
    public void tabelaCliente(){
        DefaultTableModel tabela1 = (DefaultTableModel) tabelaMenu1.getModel();
        tabela1.setNumRows(0);
        ClienteDAO clDao = new ClienteDAO();
        
        for(Cliente c : clDao.read()){
        
            tabela1.addRow(new Object[]{
                
                c.getId_quarto(),
                c.getSituacao(),
                c.getNome()  
            });
            
        }
    
    }
    
    public void combBoxP1(){
        
        QuartoDAO qtDao = new QuartoDAO();

            for(Quarto q : qtDao.read()){
                if(q.getEstado().equals("vago")){
                    cbQuartos.addItem(q);
                }
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelBase = new javax.swing.JPanel();
        barraLateral = new javax.swing.JPanel();
        menu1 = new javax.swing.JButton();
        menu2 = new javax.swing.JButton();
        menu4 = new javax.swing.JButton();
        areaTrabalho = new javax.swing.JPanel();
        area1 = new javax.swing.JPanel();
        barraBts = new javax.swing.JPanel();
        btCheckin = new javax.swing.JButton();
        btCheckout = new javax.swing.JButton();
        btAtualizar = new javax.swing.JButton();
        btDetalhes = new javax.swing.JButton();
        btPesquisa = new javax.swing.JButton();
        scrollTabela1 = new javax.swing.JScrollPane();
        tabelaMenu1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        barraPesquisa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        clCpf = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        cbQuartos = new javax.swing.JComboBox<>();
        area2 = new javax.swing.JPanel();
        barraBts1 = new javax.swing.JPanel();
        qtAdinicionar = new javax.swing.JButton();
        qtAtualizar = new javax.swing.JButton();
        qtExcluir = new javax.swing.JButton();
        btDetalhes1 = new javax.swing.JButton();
        qtForm = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        qtPeriodo = new javax.swing.JComboBox<>();
        qtNumero = new javax.swing.JTextField();
        qtAndar = new javax.swing.JTextField();
        qtPreco = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        qtTabela = new javax.swing.JTable();
        telaLogin = new javax.swing.JPanel();
        login = new javax.swing.JPanel();
        recupLogin = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hotelaria");
        setBackground(new java.awt.Color(244, 244, 244));
        getContentPane().setLayout(new java.awt.CardLayout());

        painelBase.setBackground(new java.awt.Color(247, 247, 247));
        painelBase.setPreferredSize(new java.awt.Dimension(900, 550));

        barraLateral.setBackground(new java.awt.Color(0, 102, 102));

        menu1.setBackground(new java.awt.Color(0, 102, 102));
        menu1.setFont(new java.awt.Font("Nunito Sans", 0, 18)); // NOI18N
        menu1.setForeground(new java.awt.Color(255, 255, 255));
        menu1.setText("Clientes");
        menu1.setBorderPainted(false);
        menu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu1.setFocusPainted(false);
        menu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu1ActionPerformed(evt);
            }
        });

        menu2.setBackground(new java.awt.Color(0, 102, 102));
        menu2.setFont(new java.awt.Font("Nunito Sans", 0, 18)); // NOI18N
        menu2.setForeground(new java.awt.Color(255, 255, 255));
        menu2.setText("Quartos");
        menu2.setBorderPainted(false);
        menu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu2.setFocusPainted(false);
        menu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu2ActionPerformed(evt);
            }
        });

        menu4.setBackground(new java.awt.Color(0, 102, 102));
        menu4.setFont(new java.awt.Font("Nunito Sans", 0, 18)); // NOI18N
        menu4.setForeground(new java.awt.Color(255, 255, 255));
        menu4.setText("Ajuda");
        menu4.setBorderPainted(false);
        menu4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu4.setFocusPainted(false);
        menu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout barraLateralLayout = new javax.swing.GroupLayout(barraLateral);
        barraLateral.setLayout(barraLateralLayout);
        barraLateralLayout.setHorizontalGroup(
            barraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menu2, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
            .addComponent(menu4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        barraLateralLayout.setVerticalGroup(
            barraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraLateralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menu1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menu2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menu4)
                .addContainerGap())
        );

        areaTrabalho.setBackground(new java.awt.Color(229, 229, 229));
        areaTrabalho.setLayout(new java.awt.CardLayout());

        area1.setBackground(new java.awt.Color(255, 255, 255));
        area1.setForeground(new java.awt.Color(0, 0, 0));

        barraBts.setBackground(new java.awt.Color(255, 255, 255));
        barraBts.setPreferredSize(new java.awt.Dimension(645, 50));

        btCheckin.setBackground(new java.awt.Color(102, 102, 102));
        btCheckin.setForeground(new java.awt.Color(255, 255, 255));
        btCheckin.setText("Check-in");
        btCheckin.setBorderPainted(false);
        btCheckin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCheckin.setFocusPainted(false);
        btCheckin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCheckinActionPerformed(evt);
            }
        });

        btCheckout.setBackground(new java.awt.Color(102, 102, 102));
        btCheckout.setForeground(new java.awt.Color(255, 255, 255));
        btCheckout.setText("Check-out");
        btCheckout.setBorderPainted(false);
        btCheckout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCheckout.setFocusPainted(false);
        btCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCheckoutActionPerformed(evt);
            }
        });

        btAtualizar.setBackground(new java.awt.Color(102, 102, 102));
        btAtualizar.setForeground(new java.awt.Color(255, 255, 255));
        btAtualizar.setText("Atualizar");
        btAtualizar.setBorderPainted(false);
        btAtualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAtualizar.setFocusPainted(false);
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        btDetalhes.setBackground(new java.awt.Color(102, 102, 102));
        btDetalhes.setForeground(new java.awt.Color(255, 255, 255));
        btDetalhes.setText("Detalhes");
        btDetalhes.setBorderPainted(false);
        btDetalhes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btDetalhes.setFocusPainted(false);
        btDetalhes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDetalhesActionPerformed(evt);
            }
        });

        btPesquisa.setBackground(new java.awt.Color(102, 102, 102));
        btPesquisa.setForeground(new java.awt.Color(255, 255, 255));
        btPesquisa.setText("Pesquisar");
        btPesquisa.setBorderPainted(false);
        btPesquisa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btPesquisa.setFocusPainted(false);

        javax.swing.GroupLayout barraBtsLayout = new javax.swing.GroupLayout(barraBts);
        barraBts.setLayout(barraBtsLayout);
        barraBtsLayout.setHorizontalGroup(
            barraBtsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraBtsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btCheckin, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btDetalhes, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        barraBtsLayout.setVerticalGroup(
            barraBtsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barraBtsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(barraBtsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCheckin)
                    .addComponent(btCheckout)
                    .addComponent(btAtualizar)
                    .addComponent(btDetalhes)
                    .addComponent(btPesquisa))
                .addGap(13, 13, 13))
        );

        scrollTabela1.setBackground(new java.awt.Color(255, 255, 255));
        scrollTabela1.setBorder(null);

        tabelaMenu1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tabelaMenu1.setForeground(new java.awt.Color(0, 0, 0));
        tabelaMenu1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº", "Situação", "Cliente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaMenu1.setGridColor(new java.awt.Color(255, 255, 255));
        tabelaMenu1.setSelectionBackground(new java.awt.Color(0, 102, 102));
        tabelaMenu1.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tabelaMenu1.getTableHeader().setReorderingAllowed(false);
        scrollTabela1.setViewportView(tabelaMenu1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        barraPesquisa.setForeground(new java.awt.Color(102, 102, 102));
        barraPesquisa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel3.setText("Nome");

        jLabel6.setText("CPF");

        try {
            clCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel7.setText("Quarto");

        cbQuartos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbQuartosItemStateChanged(evt);
            }
        });
        cbQuartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbQuartosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(clCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(jLabel7)
                        .addGap(41, 41, 41)
                        .addComponent(cbQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(barraPesquisa))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(barraPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(clCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cbQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout area1Layout = new javax.swing.GroupLayout(area1);
        area1.setLayout(area1Layout);
        area1Layout.setHorizontalGroup(
            area1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barraBts, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 893, Short.MAX_VALUE)
            .addGroup(area1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollTabela1)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        area1Layout.setVerticalGroup(
            area1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(area1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barraBts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollTabela1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                .addContainerGap())
        );

        areaTrabalho.add(area1, "area1");

        area2.setBackground(new java.awt.Color(255, 255, 255));

        barraBts1.setBackground(new java.awt.Color(255, 255, 255));
        barraBts1.setPreferredSize(new java.awt.Dimension(645, 50));

        qtAdinicionar.setBackground(new java.awt.Color(102, 102, 102));
        qtAdinicionar.setForeground(new java.awt.Color(255, 255, 255));
        qtAdinicionar.setText("Adicionar");
        qtAdinicionar.setBorderPainted(false);
        qtAdinicionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        qtAdinicionar.setFocusPainted(false);
        qtAdinicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtAdinicionarActionPerformed(evt);
            }
        });

        qtAtualizar.setBackground(new java.awt.Color(102, 102, 102));
        qtAtualizar.setForeground(new java.awt.Color(255, 255, 255));
        qtAtualizar.setText("Atualizar");
        qtAtualizar.setBorderPainted(false);
        qtAtualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        qtAtualizar.setFocusPainted(false);
        qtAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtAtualizarActionPerformed(evt);
            }
        });

        qtExcluir.setBackground(new java.awt.Color(102, 102, 102));
        qtExcluir.setForeground(new java.awt.Color(255, 255, 255));
        qtExcluir.setText("Excluir");
        qtExcluir.setBorderPainted(false);
        qtExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        qtExcluir.setFocusPainted(false);
        qtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtExcluirActionPerformed(evt);
            }
        });

        btDetalhes1.setBackground(new java.awt.Color(102, 102, 102));
        btDetalhes1.setForeground(new java.awt.Color(255, 255, 255));
        btDetalhes1.setText("Detalhes");
        btDetalhes1.setBorderPainted(false);
        btDetalhes1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btDetalhes1.setFocusPainted(false);
        btDetalhes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDetalhes1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout barraBts1Layout = new javax.swing.GroupLayout(barraBts1);
        barraBts1.setLayout(barraBts1Layout);
        barraBts1Layout.setHorizontalGroup(
            barraBts1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barraBts1Layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addGroup(barraBts1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btDetalhes1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtAdinicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );
        barraBts1Layout.setVerticalGroup(
            barraBts1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barraBts1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(qtAdinicionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(qtAtualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(qtExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btDetalhes1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        qtForm.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Número do Quarto");

        jLabel2.setText("Andar");

        jLabel4.setText("Preço");

        jLabel5.setText("Período");

        qtPeriodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "7", "30" }));

        qtNumero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        qtAndar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        qtPreco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        qtPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtPrecoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout qtFormLayout = new javax.swing.GroupLayout(qtForm);
        qtForm.setLayout(qtFormLayout);
        qtFormLayout.setHorizontalGroup(
            qtFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qtFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(qtFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(qtNumero)
                    .addComponent(qtAndar, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addGroup(qtFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(qtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(qtPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(75, 75, 75))
        );
        qtFormLayout.setVerticalGroup(
            qtFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qtFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(qtFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(qtFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(qtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtPreco))
                .addGap(18, 18, 18)
                .addGroup(qtFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(qtFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(qtAndar)
                    .addComponent(qtPeriodo, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        qtTabela.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        qtTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº", "Andar", "Preço", "Estado", "Período"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        qtTabela.setGridColor(new java.awt.Color(255, 255, 255));
        qtTabela.setSelectionBackground(new java.awt.Color(0, 102, 102));
        qtTabela.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(qtTabela);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout area2Layout = new javax.swing.GroupLayout(area2);
        area2.setLayout(area2Layout);
        area2Layout.setHorizontalGroup(
            area2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(area2Layout.createSequentialGroup()
                .addComponent(qtForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barraBts1, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        area2Layout.setVerticalGroup(
            area2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(area2Layout.createSequentialGroup()
                .addGroup(area2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(barraBts1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(qtForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        areaTrabalho.add(area2, "area2");

        javax.swing.GroupLayout painelBaseLayout = new javax.swing.GroupLayout(painelBase);
        painelBase.setLayout(painelBaseLayout);
        painelBaseLayout.setHorizontalGroup(
            painelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBaseLayout.createSequentialGroup()
                .addComponent(barraLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(areaTrabalho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelBaseLayout.setVerticalGroup(
            painelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barraLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(areaTrabalho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(painelBase, "card3");

        telaLogin.setLayout(new java.awt.CardLayout());

        login.setBackground(new java.awt.Color(0, 102, 102));
        login.setForeground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout loginLayout = new javax.swing.GroupLayout(login);
        login.setLayout(loginLayout);
        loginLayout.setHorizontalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        loginLayout.setVerticalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 624, Short.MAX_VALUE)
        );

        telaLogin.add(login, "card2");

        recupLogin.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout recupLoginLayout = new javax.swing.GroupLayout(recupLogin);
        recupLogin.setLayout(recupLoginLayout);
        recupLoginLayout.setHorizontalGroup(
            recupLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        recupLoginLayout.setVerticalGroup(
            recupLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 624, Short.MAX_VALUE)
        );

        telaLogin.add(recupLogin, "card3");

        getContentPane().add(telaLogin, "card2");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu4ActionPerformed
        Ajuda ajuda = new Ajuda(this, true);
        ajuda.setVisible(true);
    }//GEN-LAST:event_menu4ActionPerformed

    private void btCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCheckoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btCheckoutActionPerformed

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAtualizarActionPerformed

    private void btDetalhesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDetalhesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btDetalhesActionPerformed

    private void menu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu1ActionPerformed
        CardLayout c1 = (CardLayout) areaTrabalho.getLayout();
        c1.show(areaTrabalho, "area1");
    }//GEN-LAST:event_menu1ActionPerformed

    private void menu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu2ActionPerformed
        CardLayout c1 = (CardLayout) areaTrabalho.getLayout();
        c1.show(areaTrabalho, "area2");
    }//GEN-LAST:event_menu2ActionPerformed

    private void qtAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtAtualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtAtualizarActionPerformed

    private void qtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtExcluirActionPerformed

    private void btDetalhes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDetalhes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btDetalhes1ActionPerformed

    private void btCheckinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCheckinActionPerformed
        
        Quarto cb = (Quarto) cbQuartos.getSelectedItem();
        Cliente cl = new Cliente();
        int id = cb.getId_quarto(); 
        
        if((barraPesquisa.getText().equals("") | cbQuartos.getSelectedIndex()== -1) ){
            JOptionPane.showMessageDialog(null,"Os campos devem ser preenchidos!");
        } else {
           
           cl.setNome(barraPesquisa.getText());
           cl.setCpf(clCpf.getText());
           cl.setId_quarto(id);
           cl.setSituacao("quite");
           cldao.create(cl);
           
           Quarto qt = qtdao.readForId(id);
           qt.setEstado("ocupado");
           qtdao.update(qt);
           
           cbQuartos.removeAllItems();
           tabelaQuarto();
           tabelaCliente();
           combBoxP1();
        }
    }//GEN-LAST:event_btCheckinActionPerformed

    private void qtPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtPrecoActionPerformed

    private void qtAdinicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtAdinicionarActionPerformed
        
        
        
    }//GEN-LAST:event_qtAdinicionarActionPerformed

    private void cbQuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbQuartosActionPerformed

    }//GEN-LAST:event_cbQuartosActionPerformed

    private void cbQuartosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbQuartosItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbQuartosItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel area1;
    private javax.swing.JPanel area2;
    private javax.swing.JPanel areaTrabalho;
    private javax.swing.JPanel barraBts;
    private javax.swing.JPanel barraBts1;
    private javax.swing.JPanel barraLateral;
    private javax.swing.JTextField barraPesquisa;
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btCheckin;
    private javax.swing.JButton btCheckout;
    private javax.swing.JButton btDetalhes;
    private javax.swing.JButton btDetalhes1;
    private javax.swing.JButton btPesquisa;
    private javax.swing.JComboBox<Object> cbQuartos;
    private javax.swing.JFormattedTextField clCpf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel login;
    private javax.swing.JButton menu1;
    private javax.swing.JButton menu2;
    private javax.swing.JButton menu4;
    private javax.swing.JPanel painelBase;
    private javax.swing.JButton qtAdinicionar;
    private javax.swing.JTextField qtAndar;
    private javax.swing.JButton qtAtualizar;
    private javax.swing.JButton qtExcluir;
    private javax.swing.JPanel qtForm;
    private javax.swing.JTextField qtNumero;
    private javax.swing.JComboBox<String> qtPeriodo;
    private javax.swing.JTextField qtPreco;
    private javax.swing.JTable qtTabela;
    private javax.swing.JPanel recupLogin;
    private javax.swing.JScrollPane scrollTabela1;
    private javax.swing.JTable tabelaMenu1;
    private javax.swing.JPanel telaLogin;
    // End of variables declaration//GEN-END:variables
}
